apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240109222638.0.0+build.02e9424
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240109222638.0.0+build.02e9424
  releaseNotes: |
    Release v20240109222638.0.0+build.02e9424 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-09-01-2024-12-50-48-657562101/where-for-dinner-ui-my-apps-bundle@sha256:ac758aa94096ffd54cedea3a8844cf6511d92e64167da6239b0ef463c5aad476
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

